from enum import Enum


class BuildStep(Enum):
    NOT_STARTED = "NOT_STARTED"
    STARTED = "STARTED"
    LLM_ATTACK_DATASETS_GENERATED = "LLM_ATTACK_DATASETS_GENERATED"
    INITIAL_RESTRICTIONS_GENERATED = "INITIAL_RESTRICTIONS_GENERATED"
    TOPIC_DATASETS_GENERATED = "TOPIC_DATASETS_GENERATED"
    FINAL_RESTRICTIONS_GENERATED = "FINAL_RESTRICTIONS_GENERATED"
    ATTACK_DATASETS_GENERATED = "ATTACK_DATASETS_GENERATED"
    EXPERIMENT_DATA_GENERATED = "EXPERIMENT_DATA_GENERATED"
    TOPIC_LISTS_GENERATED = "TOPIC_LISTS_GENERATED"
    AUTOTUNING = "AUTOTUNING"
    TEST_BENCHMARKING = "TEST_BENCHMARKING"
    VALIDATION_BENCHMARKING = "VALIDATION_BENCHMARKING"
    DONE = "DONE"
